server:
  ##端口
  port: 8083
  servlet:
    ##根路径
    context-path: /receivePdf
  undertow:
    max-http-post-size: -1B
spring:
  ##数据库
  datasource:
    username: sa
    #password: docus702
    password: AbcXyz123
    url: jdbc:sqlserver://localhost:1433;databaseName=emr_record
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #上传文件大小
  servlet:
    multipart:
      file-size-threshold: 0
      max-file-size: 10240000
      max-request-size: 10240000
##日志
logging:
  level:
    org.springframework.web: ERROR
    com.yiibai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    #name: C:/logs/RecivePdfServer/RecivePdfServer.log
    name: D:/logs/RecivePdfServer/RecivePdfServer.log
#mybatis路径配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  mybatis.type-aliases-package: com.jiashi.entity
  mybatis.configuration.map-underscore-to-camel-case: true

##保存pdf文件根目录
#pdfFileSrc: C:\pdf\
pdfFileSrc: G:\pdf\

